apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job-example
spec:
  completions: 10
  parallelism: 2
  completionMode: Indexed
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
      containers:
      - name: pre-processor
        image: python:3
        command: ["/bin/bash", "/data/wiki-text.sh"]
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Never
      tolerations:
      - key: nautilus.io/reservation
        operator: Equal
        value: csu-tide
        effect: NoSchedule
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: index-volume
