apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nautilus.io/csu-tide
            operator: Exists
  tolerations:
  - key: nautilus.io/reservation
    operator: Equal
    value: csu-tide
    effect: NoSchedule
  containers:
  - name: jupyter
    image: quay.io/jupyter/pytorch-notebook:cuda12-2024-07-29
    command: ["jupyter", "lab"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: 2
        memory: 4Gi
      requests:
        nvidia.com/gpu: 1
        cpu: 2
        memory: 4Gi
    volumeMounts:
    - name: jupyter-volume
      mountPath: /home/jovyan
  volumes:
  - name: jupyter-volume
    persistentVolumeClaim:
      claimName: jupyter-volume
